# Deploy staging theme
name: Deploy osi-theme to staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy theme
    runs-on: ubuntu-latest
 
    steps:  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Deploy     
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          ARGS: >-  
            -rltgoDzvO
            --exclude='.git'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_PROD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_PROD }}
          TARGET: /home/wp_axcmcq/stemaf15dreampress.stage.site/wp-content/themes/osi-theme/
